= Demo to fetch old / new version of document using Elasticsearch Java High Level Rest Client


This project gives a small demo, which update document and fetch old / new version of document(s) from elasticsearch server for `update`, `update_by_query`, and `index` API request.

Elasticsearch v7.7.1 with additional feature from my other project link:https://github.com/vikashkumar-19/elasticsearch[Elasticsearch] is being used while this project as a server side to update and fetch document from Rest Client.

== Dependencies
- elasticsearch.jar (local jar build from link:https://github.com/vikashkumar-19/elasticsearch[Elasticsearch] to reflect my required changes)

- elasticsearch-rest-high-level-client.jar [ local jar build from link:https://github.com/vikashkumar-19/elasticsearch[rest-high-level-client] which reflect small changes of RequestConverter.java ]

- elasticsearch-rest-high-level-client [ published here link:https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high.html[elastic.co] ]

- log4j

- slf4j (slf4j-simple and slf4j-api)

- junit

== High-level Rest Client
It accepts request objects as an argument and returns response objects so that request marshalling and response un-marshalling is handled by the client itself. You can go through this official documentation link:https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-getting-started.html[High-Level Rest Client] for other Rest APIs.

Following are examples showing the working of three APIs.
```
// Initialization
RestHighLevelClient client = new RestHighLevelClient( new RestClient.builder(
                                new HttpHost("localhost", 9200, "http")));
```
Index Request:
```
// source
XContentBuilder builder = XContentFactory.jsonBuilder();
builder.startObject();
    {
        builder.field("counter", 1);
    }
builder.endObject();

// request
IndexRequest request = new IndexRequest("index_test").id("1")
                .setRefreshPolicy(WriteRequest.RefreshPolicy.IMMEDIATE)
                .source(builder)
                .fetchSource(true);

IndexResponse response = client.index(request, RequestOptions.DEFAULT);

// get updated document
GetResult result = response.getGetResult();
Map<String, Object> source = result.getSource();
```
Update Request:
```
UpdateRequest request = new UpdateRequest("index_test","1")
        .script( new Script("ctx._source.counter++"))
        .fetchSource(true)
        .fetchSourceOld(false)
        .setRefreshPolicy(WriteRequest.RefreshPolicy.IMMEDIATE);

UpdateResponse response = client.update(request, RequestOptions.DEFAULT);

// extract document fields
GetResult result = response.getGetResult();
Map<String, Object> source = result.getSource();
```
Update_by_query Request:
```
UpdateByQueryRequest request = new UpdateByQueryRequest("index_test")
            .setQuery(new TermQueryBuilder("counter",2))
            .setScript(new Script("ctx._source.counter=6"))
            .fetchSource(true)
            .fetchSourceOld(true)
            .setRefresh(true);

BulkByScrollResponse response = client.updateByQuery(request, RequestOptions.DEFAULT);

// document(s) old version
List<GetResult> sourceOld = response.getGetResultOld();

// document(s) new version
List<GetResult> source = response.getGetResult();
```
== Testing
Run all test defined in test section of project. This tests *index*, *update*, and *update_by_query* API to just fetch document fields.
```
mvn test
```
